# Generated by Django 3.2.6 on 2021-08-09 15:44

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='')),
            ],
            bases=(models.Model, app.models.WithDate),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileType', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('STUDENT', 'Student'), ('SYNDICATE', 'Syndicate')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('documentType', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=5, null=True)),
                ('document', models.CharField(max_length=50, null=True)),
            ],
            bases=(models.Model, app.models.WithDate),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(null=True)),
                ('formLogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flogo', to='app.fileupload')),
                ('printLogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plogo', to='app.fileupload')),
            ],
            bases=(models.Model, app.models.WithDate),
        ),
    ]
