# Generated by Django 3.2.6 on 2021-08-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210809_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='formLogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_formLogos', to='app.fileupload'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='printLogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_printLogos', to='app.fileupload'),
        ),
    ]
